import Link from "next/link";
import { ArrowLeft, ArrowRight, CheckCircle2, Headphones, MessageCircle, Trophy } from "lucide-react";

const steps = [
  { icon: Headphones, title: "Mashqni tanlang", text: "Bosh sahifadagi mashqlar darajalar bo‘yicha berilgan. Qulf belgisi bor mashq oldingisini kamida 90% o‘zlashtirgandan keyin ochiladi." },
  { icon: Headphones, title: "Tinglang va yozing", text: "Boshlash tugmasini bosing. Video qisqa jumlalarni navbatma-navbat qo‘yadi; eshitgan koreyscha jumlangizni yozing. Mashqni istalgan payt yakunlashingiz mumkin." },
  { icon: CheckCircle2, title: "Natijani ko‘ring", text: "Mashq tugagach o‘zlashtirish foizi ko‘rsatiladi. Jumlalarning kamida 90 foizi to‘g‘ri bo‘lsa, to‘liq matn profilingizda ochiladi va navbatdagi mashqqa yo‘l ochiladi." },
  { icon: MessageCircle, title: "Fikr almashing", text: "Mashq yakunidagi muhokamada shu mashq haqida yozing. Jamoa sahifasida boshqa o‘rganuvchilarga alohida xabar yuborish va ularni yulduz bilan baholash mumkin." },
  { icon: Trophy, title: "Rivojlanishni kuzating", text: "Profilingizda jami ball, bosqich, bajarilgan mashqlar va ochilgan to‘liq matnlar saqlanadi." },
];

export default function GuidePage() {
  return <main className="min-h-screen bg-[#f8f9fc] px-4 pb-12 text-[#1e2030] sm:px-6"><header className="mx-auto flex h-[70px] max-w-3xl items-center"><Link href="/" className="flex items-center gap-2 text-[13px] font-semibold text-[#737587]"><ArrowLeft size={16}/> Bosh sahifa</Link></header><section className="mx-auto max-w-3xl pt-5"><span className="grid h-12 w-12 place-items-center rounded-2xl bg-[#eeedff] text-[#635bdb]"><Headphones size={22}/></span><p className="mt-5 text-[11px] font-bold tracking-[1.3px] text-[#7770d2]">KLEVELTEST QO‘LLANMASI</p><h1 className="mt-1 text-[30px] font-bold tracking-[-.8px]">Qanday ishlaydi?</h1><p className="mt-2 text-sm text-[#858697]">Tinglab yozish mashqlarini bajarish va keyingi bosqichga o‘tish bo‘yicha qisqa yo‘riqnoma.</p><div className="mt-7 space-y-3">{steps.map((step, index) => <article key={step.title} className="flex gap-4 rounded-2xl border border-[#e8e9f0] bg-white p-5"><span className="grid h-10 w-10 shrink-0 place-items-center rounded-xl bg-[#f3f2ff] text-[#635bdb]"><step.icon size={18}/></span><div><p className="text-[10px] font-bold tracking-wide text-[#8c8d9a]">0{index + 1}</p><h2 className="mt-0.5 text-sm font-bold">{step.title}</h2><p className="mt-1 text-[12px] leading-5 text-[#77798a]">{step.text}</p></div></article>)}</div><div className="mt-6 flex flex-col gap-3 sm:flex-row"><Link href="/" className="flex items-center justify-center gap-2 rounded-xl bg-[#635bdb] px-5 py-3 text-sm font-semibold text-white">Mashqlarga qaytish <ArrowRight size={15}/></Link><Link href="/community" className="flex items-center justify-center gap-2 rounded-xl border border-[#e2e2eb] bg-white px-5 py-3 text-sm font-semibold text-[#5b5d6e]">Jamoani ko‘rish <MessageCircle size={15}/></Link></div></section></main>;
}
